package GUI_CALC;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        tfResult = new javax.swing.JTextField();
        panel3 = new javax.swing.JPanel();
        btPhamTram = new javax.swing.JButton();
        btCE = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btEnd = new javax.swing.JButton();
        btNgichDao = new javax.swing.JButton();
        btABS = new javax.swing.JButton();
        btSQRT = new javax.swing.JButton();
        btDivide = new javax.swing.JButton();
        btNum7 = new javax.swing.JButton();
        btNum8 = new javax.swing.JButton();
        btNum9 = new javax.swing.JButton();
        btMultiply = new javax.swing.JButton();
        btNum4 = new javax.swing.JButton();
        btNum5 = new javax.swing.JButton();
        btNum6 = new javax.swing.JButton();
        btMinus = new javax.swing.JButton();
        btNum1 = new javax.swing.JButton();
        btNum2 = new javax.swing.JButton();
        btNum3 = new javax.swing.JButton();
        btPlus = new javax.swing.JButton();
        btPlusMinus = new javax.swing.JButton();
        btNum0 = new javax.swing.JButton();
        btSubtract = new javax.swing.JButton();
        btEquals = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        btMC = new javax.swing.JButton();
        btMR = new javax.swing.JButton();
        btMPlus = new javax.swing.JButton();
        btMMinus = new javax.swing.JButton();
        btM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb1.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lb1.setText("Casio");

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tfResult.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        tfResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfResult.setText("0");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfResult, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfResult, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel3.setLayout(new java.awt.GridLayout(6, 4, 5, 5));

        btPhamTram.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btPhamTram.setText("%");
        btPhamTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPhamTramActionPerformed(evt);
            }
        });
        panel3.add(btPhamTram);

        btCE.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btCE.setText("CE");
        panel3.add(btCE);

        btC.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btC.setText("C");
        panel3.add(btC);

        btEnd.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btEnd.setText("End");
        panel3.add(btEnd);

        btNgichDao.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNgichDao.setText("1/x");
        panel3.add(btNgichDao);

        btABS.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btABS.setText("ABS");
        panel3.add(btABS);

        btSQRT.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btSQRT.setText("SQRT");
        panel3.add(btSQRT);

        btDivide.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btDivide.setText("/");
        panel3.add(btDivide);

        btNum7.setBackground(new java.awt.Color(255, 255, 255));
        btNum7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum7.setText("7");
        panel3.add(btNum7);

        btNum8.setBackground(new java.awt.Color(255, 255, 255));
        btNum8.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum8.setText("8");
        btNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNum8ActionPerformed(evt);
            }
        });
        panel3.add(btNum8);

        btNum9.setBackground(new java.awt.Color(255, 255, 255));
        btNum9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum9.setText("9");
        panel3.add(btNum9);

        btMultiply.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btMultiply.setText("x");
        btMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplyActionPerformed(evt);
            }
        });
        panel3.add(btMultiply);

        btNum4.setBackground(new java.awt.Color(255, 255, 255));
        btNum4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum4.setText("4");
        panel3.add(btNum4);

        btNum5.setBackground(new java.awt.Color(255, 255, 255));
        btNum5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum5.setText("5");
        panel3.add(btNum5);

        btNum6.setBackground(new java.awt.Color(255, 255, 255));
        btNum6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum6.setText("6");
        panel3.add(btNum6);

        btMinus.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btMinus.setText("-");
        panel3.add(btMinus);

        btNum1.setBackground(new java.awt.Color(255, 255, 255));
        btNum1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum1.setText("1");
        panel3.add(btNum1);

        btNum2.setBackground(new java.awt.Color(255, 255, 255));
        btNum2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum2.setText("2");
        panel3.add(btNum2);

        btNum3.setBackground(new java.awt.Color(255, 255, 255));
        btNum3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum3.setText("3");
        panel3.add(btNum3);

        btPlus.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btPlus.setText("+");
        panel3.add(btPlus);

        btPlusMinus.setBackground(new java.awt.Color(255, 255, 255));
        btPlusMinus.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btPlusMinus.setText("+/-");
        panel3.add(btPlusMinus);

        btNum0.setBackground(new java.awt.Color(255, 255, 255));
        btNum0.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btNum0.setText("0");
        panel3.add(btNum0);

        btSubtract.setBackground(new java.awt.Color(255, 255, 255));
        btSubtract.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btSubtract.setText(".");
        panel3.add(btSubtract);

        btEquals.setBackground(new java.awt.Color(102, 255, 255));
        btEquals.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btEquals.setText("=");
        panel3.add(btEquals);

        panel2.setLayout(new java.awt.GridLayout(1, 5));

        btMC.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btMC.setText("MC");
        panel2.add(btMC);

        btMR.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btMR.setText("MR");
        panel2.add(btMR);

        btMPlus.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btMPlus.setText("M+");
        panel2.add(btMPlus);

        btMMinus.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btMMinus.setText("M-");
        panel2.add(btMMinus);

        btM.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btM.setText("M");
        panel2.add(btM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lb1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPhamTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPhamTramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPhamTramActionPerformed

    private void btNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNum8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNum8ActionPerformed

    private void btMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMultiplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btABS;
    private javax.swing.JButton btC;
    private javax.swing.JButton btCE;
    private javax.swing.JButton btDivide;
    private javax.swing.JButton btEnd;
    private javax.swing.JButton btEquals;
    private javax.swing.JButton btM;
    private javax.swing.JButton btMC;
    private javax.swing.JButton btMMinus;
    private javax.swing.JButton btMPlus;
    private javax.swing.JButton btMR;
    private javax.swing.JButton btMinus;
    private javax.swing.JButton btMultiply;
    private javax.swing.JButton btNgichDao;
    private javax.swing.JButton btNum0;
    private javax.swing.JButton btNum1;
    private javax.swing.JButton btNum2;
    private javax.swing.JButton btNum3;
    private javax.swing.JButton btNum4;
    private javax.swing.JButton btNum5;
    private javax.swing.JButton btNum6;
    private javax.swing.JButton btNum7;
    private javax.swing.JButton btNum8;
    private javax.swing.JButton btNum9;
    private javax.swing.JButton btPhamTram;
    private javax.swing.JButton btPlus;
    private javax.swing.JButton btPlusMinus;
    private javax.swing.JButton btSQRT;
    private javax.swing.JButton btSubtract;
    private javax.swing.JLabel lb1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JTextField tfResult;
    // End of variables declaration//GEN-END:variables
}
